- name: Install JDK8
  become: yes
  become_user: vagrant
  command: yay --noconfirm --answeredit none -S jdk8 --noconfirm


- name: Default java
  become: yes
  become_user: root
  command: archlinux-java set java-8-jdk

- name: Download and unarchive flink
  become: yes
  become_user: root
  unarchive:
    src: http://ftp.man.poznan.pl/apache/flink/flink-1.6.2/flink-1.6.2-bin-scala_2.11.tgz
    dest: /opt
    remote_src: yes

- name: Link flink
  become: yes
  become_user: root
  file:
    src: /opt/flink-1.6.2
    dest: /opt/apache-flink
    state: link

- name: "Alias start-cluster"
  become: yes
  become_user: root
  raw: "echo 'alias start-cluster=\"/opt/apache-flink/bin/start-cluster.sh\"' > /etc/profile.d/flink.sh"

- name: "Alias flink"
  become: yes
  become_user: root
  raw: "echo 'alias flink=\"/opt/apache-flink/bin/flink\"' >> /etc/profile.d/flink.sh"